apiVersion: "v1"
kind: "List"
items:
-
  apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      provider: "openshift"
      component: "elasticsearch"
    name: "es-logging"
  spec:
    ports:
    -
      port: 9200
      targetPort: 9200
    selector:
      provider: "openshift"
      component: "elasticsearch"
-
  apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      provider: "openshift"
      component: "elasticsearch"
    name: "es-logging-cluster"
  spec:
    portalIP: "None"
    ports:
    -
      port: 9300
      targetPort: 9300
    selector:
      provider: "openshift"
      component: "elasticsearch"
-
  apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    labels:
      provider: "openshift"
      component: "elasticsearch"
    name: "elasticsearch"
  spec:
    replicas: 1
    selector:
      provider: "openshift"
      component: "elasticsearch"
    template:
      metadata:
        labels:
          provider: "openshift"
          component: "elasticsearch"
      spec:
        containers:
          -
            env:
            -
              name: "KUBERNETES_TRUST_CERT"
              value: "true"
            -
              name: "SERVICE_DNS"
              value: "es-logging-cluster"
            -
              name: "CLUSTER_NAME"
              value: "elasticsearch"
            image: "openshift/elasticsearch:v1"
            name: "elasticsearch"
            ports:
            -
              containerPort: 9200
              name: "http"
            -
              containerPort: 9300
              name: "transport"
-
  apiVersion: v1
  kind: Pod
  metadata:
    name: fluentd-elasticsearch
  spec:
    containers:
    - name: fluentd-elasticsearch
      image: openshift/fluentd:v1
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 100m
      volumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
      env:
      - name: "ES_HOST"
        value: "es-logging"
      - name: "ES_PORT"
        value: "9200"
    volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
-
  apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "kibana"
  spec:
    ports:
      -
        port: 80
        targetPort: "kibana-port"
    selector:
      provider: openshift
      component: "kibana"
-
  apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    name: "kibana"
    labels:
      provider: openshift
      component: "kibana"
  spec:
    replicas: 1
    selector:
      component: "kibana"
    template:
      metadata:
        name: "kibana"
        labels:
          provider: openshift
          component: "kibana"
      spec:
        containers:
          -
            name: "kibana"
            image: "openshift/kibana:v1"
            ports:
              -
                name: "kibana-port"
                containerPort: 5601
            env:
              - name: "ES_HOST"
                value: "es-logging"
              - name: "ES_PORT"
                value: "9200"
